# Generated by Django 3.1 on 2021-05-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210512_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(blank=True, max_length=256, upload_to='media/'),
        ),
    ]
