# Generated by Django 4.0.2 on 2022-03-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.auction'),
        ),
    ]
